export const en = {
  nav: { 
    lang: "EN", 
    langOther: "RU",
    roots: "Roots",
    leaf: "Leaf",
    portfolio: "Portfolio",
    standards: "Standards",
    founders: "Founders",
    opening: "Contact",
  },
  ageGate: {
    brand: "BISHKEK TOBACCO MANUFACTURING",
    question: "Are you 18 or older?",
    sub: "This site contains information about tobacco products.",
    yes: "Yes, enter",
    no: "No",
  },
  hero: {
    eyebrow: "BISHKEK TOBACCO MANUFACTURING · EST. 2026",
    title: "American leaf.\nMade in Kyrgyzstan.",
    sub: "The first tobacco manufacturing house in Kyrgyzstan. Opening Q1 2027.",
    progressLabel: "FACILITY READINESS",
    progressValue: "70%",
    progressNote: "Equipment installation · Launch Q1 2027",
  },
  roots: {
    eyebrow: "OUR INSPIRATION",
    title: "The oldest craft.\nA new house.",
    body: [
      "Tobacco was first cultivated by Native Americans more than three thousand years ago. They understood the leaf, its curing, its patience. Early settlers learned from them — and that knowledge became the foundation of the American tobacco tradition: Virginia, Kentucky, the Carolinas.",
      "Four centuries later, American tobacco is the world standard. Respected in quality. Demanding in its craft.",
      "We carry that heritage forward. Into Bishkek. Into Central Asia. Into a new house built on old knowledge.",
    ],
    closing: "American leaf. American standards. Made in Kyrgyzstan.",
  },
  leaf: {
    eyebrow: "THE FOUNDATION",
    title: "Four leaves.\nNo substitutes.",
    intro:
      "We use only four tobacco varieties — Virginia, Kentucky, Oriental, and Burley. Every leaf is grown on American soil. Every blend is built from whole leaf.",
    rule: "No reconstituted tobacco. No blown-up stem. No chemical flavouring.",
    leaves: [
      { name: "Virginia", note: "Bright, sweet. The backbone of American blends." },
      { name: "Kentucky", note: "Earthy, bold. The Southern classic." },
      { name: "Oriental", note: "Delicate, aromatic. From the eastern Mediterranean. Cured under sun." },
      { name: "Burley", note: "Airy, full-bodied. Richness that lets a blend breathe." },
    ],
  },
  preparation: {
    eyebrow: "WHERE WE ARE",
    title: "Seventy percent ready.",
    body: [
      "Our facility in Bishkek is being built with care. Equipment is in transit. Staff is training. Every room, every machine, every process is being set up the right way.",
      "When we open our doors in the first quarter of 2027, we will produce without shortcuts.",
    ],
    markers: ["70% BUILT", "Q1 2027 OPENING", "ISO 9001:2015 READY"],
  },
  portfolio: {
    eyebrow: "THE HOUSE",
    title: "Six brands.\nOne roof.",
    sub: "Licensed for manufacturing at our Bishkek facility starting Q1 2027.",
    brands: [
      {
        name: "NEMIROFF",
        kind: "Classic, Premium, Cigarillos.",
        meta: "35 SKU · 84 / 100mm",
        notes: "Red · Gold · Blue · Sky · Platinum · Black & Gold · Aqua · Menthol · Cognac · Cherry · Rum · Chocolate",
      },
      {
        name: "NEW YORK NEW YORK",
        kind: "Classic and flavoured lines.",
        meta: "20+ SKU · 84 / 100mm",
        notes: "Black Platinum · Cognac · Rum · Chocolate · Cherry · Menthol · White Platinum",
      },
      {
        name: "PATRIOT",
        kind: "Classic hard-pack and Little Cigars.",
        meta: "12+ SKU · 84mm",
        notes: "Red · Gold · Blue · Platinum · Green · Menthol · Cognac · Rum · Chocolate",
      },
      {
        name: "CHEROKEE",
        kind: "Heritage blends drawn from Native American tobacco tradition.",
        meta: "Heritage line",
        notes: "Rich, full-bodied, authentic.",
      },
      {
        name: "ANTI-VIRUS",
        kind: "Specialty line.",
        meta: "Limited release",
        notes: "Reserved batches only.",
      },
      {
        name: "FORTUNOFF",
        kind: "Premium craft line.",
        meta: "For the demanding palate",
        notes: "A house statement.",
      },
    ],
  },
  formats: {
    eyebrow: "WHAT TO EXPECT",
    title: "Every size.\nEvery taste.",
    sub: "We produce in the full international cigarette sizing range and in eighteen cigarillo flavour profiles.",
    formatsTitle: "CIGARETTE FORMATS",
    formats: [
      { name: "Kings", note: "84mm · full-size classic" },
      { name: "Compact", note: "standard compact pack" },
      { name: "Slim", note: "slender profile" },
      { name: "Super Slim", note: "narrow elegant format" },
    ],
    flavoursTitle: "CIGARILLO FLAVOURS",
    flavours: [
      { name: "Cognac", note: "deep, woody, aged" },
      { name: "Rum", note: "sweet, dark, island spice" },
      { name: "Chocolate", note: "rich, smooth, bittersweet" },
      { name: "Cherry", note: "tart, bright, playful" },
      { name: "Menthol", note: "crisp, clean, mountain air" },
      { name: "Paper Mint", note: "cooling, fresh, light" },
      { name: "Black Platinum", note: "dark, robust, premium" },
      { name: "White Platinum", note: "refined, balanced" },
      { name: "Gold", note: "classic, elegant, warm" },
    ],
  },
  standards: {
    eyebrow: "OUR PROMISE",
    title: "No shortcuts.",
    pillars: [
      { value: "100%", label: "Organic. American-grown. Single-leaf." },
      { value: "ISO 9001:2015", label: "International quality standard." },
      { value: "≤ 10 / 1.0 / 10", label: "TNCO within international norms." },
    ],
    rule: "No reconstituted tobacco. No blown-up stem. No chemical flavouring.",
  },
  founders: {
    eyebrow: "THE PEOPLE",
    title: "Two founders.\nOne mission.",
    cards: [
      {
        name: "TAIR ABDYSH",
        role: "Founder & CEO",
        bio: "Building Kyrgyzstan's first tobacco manufacturing house. Bringing American standards and Native American heritage to Central Asia.",
        meta: "Bishkek · 1998",
      },
      {
        name: "AIDAR BARAKANOV",
        role: "Co-founder",
        bio: "Operations and strategic development. Co-architect of BTM's path to market.",
        meta: "Bishkek · 2001",
      },
    ],
  },
  opening: {
    title: "Q1 2027.",
    sub: "The first batch is on its way.",
    body: "Be the first to know when our doors open.",
    contact: "For early enquiries:",
    email: "press@kyrgyztobacco.kg",
    cta: "Write to us",
  },
  footer: {
    legalTitle: "LEGAL",
    legal: [
      "BISHKEK TOBACCO MANUFACTURING LLC",
      "OsOO «Бишкек Тобакко Мануфэкчуринг»",
      "Tax ID (INN): 00705201310223",
      "Reg. No.: 129670-3301-ООО",
      "OKPO: 28097219",
      "Kyrgyz Republic · Bishkek",
      "Pervomaisky district",
      "Ch. Aitmatov Avenue 54, apt. 13 · 720044",
    ],
    contactTitle: "CONTACT",
    contact: [
      "tair@kyrgyztobacco.kg",
      "press@kyrgyztobacco.kg",
      "partners@kyrgyztobacco.kg",
      "+996 559 777 799",
      "+996 554 420 013",
    ],
    complianceTitle: "COMPLIANCE",
    compliance: [
      "Wholesale inquiries only.",
      "Restricted to adults 18+ where legally permitted.",
      "Subject to local tobacco regulations.",
    ],
    copy: "© 2026 Bishkek Tobacco Manufacturing LLC. All rights reserved.",
    warning: "Informational site. Content intended for adults 18+.",
  },
};

export type Dict = typeof en;
